### PR TITLE
Add testnet tests for fetch-tx, fetch-balance, and watch-address

### PR DESCRIPTION
**Pull request by thecodefactory**

### CODE REVIEW

**Comment by thecodefactory** [comment]
Fails with "permission denied" -- not sure why this is ok in other configurations and not in these:

```
/bin/mkdir -p '/home/travis/build/libbitcoin/libbitcoin-explorer/my-prefix/bin'
/bin/bash ./libtool   --mode=install /usr/bin/install -c console/bx '/home/travis/build/libbitcoin/libbitcoin-explorer/my-prefix/bin'
libtool: install: /usr/bin/install -c console/.libs/bx /home/travis/build/libbitcoin/libbitcoin-explorer/my-prefix/bin/bx
/bin/mkdir -p '/usr/share/bash-completion/completions'
/usr/bin/install -c -m 644 data/bx '/usr/share/bash-completion/completions'
/usr/bin/install: cannot create regular file ‘/usr/share/bash-completion/completions/bx’: Permission denied
make[1]: *** [install-dist_bash_completionDATA] Error 1
make[1]: Leaving directory `/home/travis/build/libbitcoin/libbitcoin-explorer'
make: *** [install-am] Error 2
```

**Comment by evoskuil** [comment]
`--with-bash-completion-dir` [requires sudo](https://github.com/libbitcoin/libbitcoin-explorer/blob/master/README.md#build-notes-for-linux--macos)

**Comment by thecodefactory** [comment]
Good to know.  Suggestions on how to deal with?

**Comment by thecodefactory** [comment]
I'm not that familiar with Travis CI build containers, but is simply adding sudo to the configurations with this option a workable solution?

**Comment by evoskuil** [comment]
Probably not, since the container model precludes sudo. @pmienk had to take it out a while back in order to get onto their faster build system. That's why I don't get what's up with it just starting to be an issue.

**Comment by thecodefactory** [comment]
Ok, I'm going to test this to verify it fails, with sudo.  If it does fail, I'll then try removing this configuration for the failed platform/builds.

**Comment by evoskuil** [comment]
I think that sudo just forces it onto the slow builds.

**Comment by evoskuil** [comment]
@pmienk ?

**Comment by pmienk** [comment]
Travis containers requires sudo: false in the yml.  If you introduce sudo I
believe you'll need to change that line and all builds, not just the one
using sudo will be effected.

**Comment by thecodefactory** [comment]
@evoskuil @pmienk Ok, it sounds like this test will be fruitless.  I don't know how unfortunate removing that step would be, as we don't have tests to see if it actually works other than usage at the moment.  Ok to try that?

**Comment by pmienk** [comment]
I don't see a problem with trying.  I believe that the explorer project is
the longest compile though, so it's unlikely Travis will complete without
reaching a time limit.

**Comment by evoskuil** [comment]
But why hasn't it been a problem until now? That build has been non-sudo for some time.

**Comment by thecodefactory** [comment]
The tests now pass with libbitcoin/libbitcoin-build#100 as a requirement.

@evoskuil I don't know why this may have suddenly appeared.

@pmienk If you insight, please review.

This 'fix' is clearly sub-optimal since it's not well understood, but I am curious about both why it appeared now, and if it actually affects deployed configurations.

**Comment by pmienk** [comment]
It looks to me like the bash_completion package has been placed into the environment where it was not previously present.  Perhaps travis has changed their default environment.  Therefore, the 'default' path is not being treated as `$datadir/bash-completion/completions` and being placed within the prefix directory (not requiring sudo).  The proper correction would be to specify the prefix modification as the argument of the completiondir instead of using the default.

This can be seen by in differences between the failing job and the [prior](https://travis-ci.org/libbitcoin/libbitcoin-explorer/jobs/265776147) in the response to `checking for bash_completion...` .

**Pull request merged**
