### PR TITLE
Adapt to the mnemonic changes in libbitcoin

### PR DESCRIPTION
**Pull request by swansontec**
This will not build until the libbitcoin changes are merged.

### CODE REVIEW

**Comment by swansontec** [comment]
Ok, you've convinced me that the text names are a bad idea. The dictionaries should only be accessible via compile-time symbols, and any text conversion should happen at the UI level. This part makes sense.

Even so, you haven't convinced me that those symbols should be *enum* members. Why can't they be ordinary variables? Why is this:

```
enum class language
{
    en,
    es,
    ja,
    zh_Hans,
    zh_Hant,
    unknown
};
```

Better than this:

```
extern const dictionary dictionary_en;
extern const dictionary dictionary_es;
extern const dictionary dictionary_ja;
extern const dictionary dictionary_zh_Hans;
extern const dictionary dictionary_zh_Hant;
```

The enum design looks more like a historical accident than an intentional design choice. It adds complexity and limitations without any benefits that I can see.

The problem with the enum is that you end up with a type like this:

    std::map<language, const wordlist*>

This map can never contain any entries besides the 5 we have today, or the compiler will complain. Is there a reason the enum is useful? If it is, can we find some compromise that allows the user step outside the enum walled garden and define their own dictionaries?

**Comment by thecodefactory** [comment]
I find it interesting this has come full circle.  My first proposed implementation had languages as strings and after discussion, it was replaced intentionally with an enum specifically to ensure that it could not be a non-supported language (and gain the compiler enforcement, etc), which was our understanding of the bip based on the text. I realize the use case here is hot-swapping the wordlists, but I can say with certainty that it was implemented as-is because it was not a requirement for the bip as interpreted.  If this use case is to be supported, it looks like it will have to be something other than the enum.

**Comment by evoskuil** [comment]
@swansontec It seems that we are in agreement. Please review my comments on the subject in the libbitcoin pull request: https://github.com/libbitcoin/libbitcoin/pull/236

@thecodefactory The enum would not in any way restrict usage. It does however become a redundant set of symbols once we have published a set of symbolic names for the built in dictionaries. Both sets of names (enum vs. independent pointers) are finite and compiled, so they are of course equally limiting, but given the agreed changes there is no actual limitation arising from strong symbolic names. The thing that allows additional dictionaries is the passage of a list of them via the validate call (which the enum would not have prevented).

Given the valuable input from @swansontec we have added two scenarios (ad-hoc dictionary support and optional validation) which drives the implementation changes. IMO the BIPs tend to be a bit too informal and sometimes leave out important information, which it why it's so valuable to have input from as many parties as possible.

**Comment by swansontec** [comment]
I have pushed some new changes. These should compile against the latest version of the libbitcoin/libbitcoin#236 pr.

**Pull request merged**
