### PR TITLE
Add ec-decompress command.

### LINKED ISSUE #291: Create new command ec-decompress
`bx` commands will continue to accept the ambiguous `ec_point` parameters, though this will introduce the new fixed-length primitives `ec_compressed`, `ec_uncompressed`.

### PR DESCRIPTION
**Pull request by toxeus**
Closes #291

### CODE REVIEW

**Comment by toxeus** [comment]
I have run `generate.sh` from `libbitcoin-build` but it didn't update the Makefiles nor the VS build files. I've updated the Makefiles manually but I don't know what to do about the VS build files.

**Comment by evoskuil** [comment]
If it didn’t update the files with the new sources check the console output for failures. There are other things that require updating.

**Comment by toxeus** [comment]
It seems to generate code into a `output` subdirectory instead of my libbitcoin project parent directory:

> gsl/4 M: Generating output/libbitcoin-explorer/.appveyor.yml...

@evoskuil any idea what I'm doing wrong?

**Comment by evoskuil** [comment]
Not sure, but the files should be copies after generation, if it completes.

**Comment by toxeus** [comment]
Alright, I've found the problem. I forgot to clone `libbitcoin-consensus` and apparently it doesn't work without it. Not sure why it used to work before though. Updating the PR now.

**Comment by evoskuil** [comment]
All repos are required, should not have worked without it.

**Comment by toxeus** [comment]
Now, I know :wink:

**Pull request merged**
