### PR TITLE
Updates tx encode command failure due to error in output parsing

### LINKED ISSUE #419: [version2] output parser failure for scripts.
https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-tx-encode#example-3

Example 3 fails to parse, as do other encoded scripts. The scripts parse successfully via `bx script-decode` and the corresponding unit test case works. Decoding works properly in current master/v3. So this problem is limited to the v2 `output` parser.

### PR DESCRIPTION
**Pull request by thecodefactory**
Updates tx encode command failure due to error in output parsing (resolves #419)

### CODE REVIEW

**Comment by thecodefactory** [comment]
Don't merge yet. Needs additional testing.

**Comment by thecodefactory** [comment]
There's a discrepancy in https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-tx-encode#example-2 as well:

```
# version2
bx tx-encode -i 97e06e49dfdd26c5a904670971ccf4c7fe7d9da53cb379bf9b442fc9427080b3:0 -o hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i:42:baadf00dbaadf00dbaadf00dbaadf00d
0100000001b3807042c92f449bbf79b33ca59d7dfec7f4cc71096704a9c526dddf496ee0970000000000ffffffff020000000000000000286a2606000000000247140d2811498679fe9a0467a75ac7aa581476c102d27377bc0232635af8ad362a000000000000001976a91470460d449bd850f361765f70803e6e251b38250388ac00000000

# master/v3
bx tx-encode -i 97e06e49dfdd26c5a904670971ccf4c7fe7d9da53cb379bf9b442fc9427080b3:0 -o hfFGUXFPKkQ5M6LC6aEUKMsURdhw93bUdYdacEtBA8XttLv7evZkira2i:42:baadf00dbaadf00dbaadf00dbaadf00d                                                                           
0100000001b3807042c92f449bbf79b33ca59d7dfec7f4cc71096704a9c526dddf496ee0970000000000ffffffff0200000000000000003a6a3814576f496f20b0befe21f39f765e81543ebd1790ec4a03d1b5a1c2e912749d90d0fd7b16322749e301a2b0dbfe278509011564590412b2772a000000000000001976a914cc04492c12d0ddeb4cf88cfccb0d6d78d0fcd39d88ac00000000
```

The example documented has **neither** what's in master, nor v2.  So it looks like there's another bug somewhere.  With this pull request merged, the example 3 is corrected and example 2 is unchanged from the v2 version.

**Comment by evoskuil** [comment]
There was at least one error in the examples. I've updated them for both `tx-encode` and `tx-decode` so that they are simpler, correct and correlated. I've also updated the wiki for these examples to be correct for v3 script (no spaces in data elements).

**Comment by evoskuil** [comment]
Thanks for this fix!

**Comment by thecodefactory** [comment]
:+1:

**Pull request merged**
