### PR TITLE
Rebase BIP38 pull request to use master repos.

### PR DESCRIPTION
**Pull request by evoskuil**
https://github.com/libbitcoin/libbitcoin-explorer/pull/269

### CODE REVIEW

**Comment by evoskuil** [comment]
I fixed a couple of issues with test but there is also an issue with ICU. It appears that a dependency on ICU exists even when `--with-icu` is not defined.

**Comment by thecodefactory** [comment]
Ok, makes sense -- any bip38 mode that uses a passphrase (ec-lock and ec-unlock) requires ICU support for the specified normalization (similar to bip39).  I think the commands will have to be unsupported without it.  I think the ec-lock-intermediate mode could still work without ICU, but I'll double check and try to fix this up tonight.

**Comment by evoskuil** [comment]
Yes, graceful feature degradation is better than the alternatives. We don't want to require the ICU dependency for libbitcoin in general. If this requires losing entire commands I would recommend leaving the commands implemented and returning an error indicating the situation. I dislike conditional build, but I dislike difficult dependencies even more.

I'm closing my rebased PR and leaving your original open. Please rebase and then apply your update there and all should be good.

**Comment by thecodefactory** [comment]
Am working on now.

**Comment by thecodefactory** [comment]
@evoskuil I first installed explorer from your PR changes using install.sh and then rebased my bip38 explorer (only) to master with icu changes, and that worked locally but failed on travis (likely since still against master). I'm building explorer against master now locally (using install.sh but with no icu and my explorer bip-38 branch) and will pick back up tonight.  Or did you want for me to keep your rebased changes also? Just not clear from your comment and previously closed PR.

I'm any case, should be able to fix tonight.

**Comment by evoskuil** [comment]
I independently merged the change to master and v3.0.0 dependency into master. See:

https://github.com/libbitcoin/libbitcoin-explorer/blob/master/install.sh

Everything should work if built from Travis. You just need to base your changes on master.

**Pull request closed without merging**
