### PR TITLE
BIP157/158 support

### PR DESCRIPTION
**Pull request by pmienk**
Adds three fetch commands performing request/response of six message types introduced. Adds two match commands detecting membership of script or payment address within a neutrino compact filter.

### CODE REVIEW

**Comment by evoskuil** [comment]
The `match-neutrino-filter-address` command is unnecessary and inconsistent with the approach used elsewhere. It constructs a script from an address using a standard pattern, though this can be accomplished using existing commands and composition. I've anticipated adding a command to generate standard scripts, which would allow for piping, vs. composition. But in any case this command is redundant with existing capability.

**Comment by evoskuil** [comment]
Other command, option and arguments recommendations can be inferred from the modified generate.xml file.

**Comment by evoskuil** [comment]
Both before and after changes the fetch unit tests fail to terminate in the VS unit test pass.

**Comment by pmienk** [comment]
I don't know about `send-tx-node`'s tests, but when I invoke the test parameterization on the command line I get an infinite loop same as `fetch-compact-filter-*`. I believe it's related to https://github.com/libbitcoin/libbitcoin-network/blob/master/src/sessions/session_manual.cpp#L162 - absence of connection doesn't appear to invoke the handler with error. So if the server isn't reachable, I think all four commands will infinite loop. Though I'm unsure where the return would cause a reregistration of the handler. Combined with the stop handler retriggering connect, and I don't see how the session will ever invoke a handler to signal the promise of the command.

**Comment by evoskuil** [comment]
Channel start failures are handled by the network later. A failure to connect is very common in the node, lots of offline IP addresses in the address pool.

**Pull request merged**
