### PR TITLE
Remove bitcoin configuration section.

### PR DESCRIPTION
**Pull request by toxeus**
The bitcoin configuration is unused since the bc::settings parameter has been removed from the class constructors.

### CODE REVIEW

**Comment by toxeus** [comment]
The coverage has increased but coveralls marks it as failed!?

**Comment by evoskuil** [comment]
Still well below target.

**Comment by toxeus** [comment]
I don't find it intuitive to mark a PR as failed if the total coverage target is not reached. But I can live with it ;)

**Comment by evoskuil** [comment]
It is a checkin-gate failure, we are just allowing it. The allowance isn’t great, but it serves as a constant reminder to us and others of the library maturity.

**Comment by toxeus** [comment]
This PR makes the code in this repo compile against latest libbitcoin master which now includes https://github.com/libbitcoin/libbitcoin/pull/1016.

**Pull request merged**
